spring:
  application:
    name: VPS
  data:
    mongodb:
      host: localhost
      port: 27017
      database: visit-planning

server:
  port: 8081


#eureka:
#  client:
#    register-with-eureka: true
#    fetch-registry: true
#    service-url:
#      defaultZone: http://localhost:8166/eureka


endpoints:
  health:
    enabled: true
    sensitive: false